

stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/configs.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/configs.yaml
    outs:
      - data/Fire
      - data/No_Fire


    