

stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/configs.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/configs.yaml
    outs:
      - data/Fire
      - data/No_Fire

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=config/configs.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare_base_model.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - config/configs.yaml
      - params.yaml
    params: 
      - IMAGE_SIZE
      - BATCH_SIZE
      - CLASSES
      - LEARNING_RATE
    outs:
      - artifacts/base_model/VGG16_base_model.h5
      - artifacts/updated_model/updated_VGG16_base_model.h5

  prepare_callbacks:
    cmd: python src/stage_03_prepare_callbacks.py --config=config/configs.yaml --params=params.yaml
    deps:
      - src/stage_03_prepare_callbacks.py
      - src/utils/all_utils.py
      - src/utils/callbacks.py
      - config/configs.yaml
      - params.yaml
    outs:
      - artifacts/callbacks/checkpoints_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb

      
