
artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CHECKPOINTS_DIR: checkpoints
  BASE_LOG_DIR: base_log_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data

source_download_dir:
  - outside_data/Fire
  - outside_data/No_Fire

local_data_dir:
  - data/Fire
  - data/No_Fire

